/*
 * Copyright 2008-2014 VTeam Financial Service Group All Rights Reserved.
 *//*

package com.bywin.baoli.clinet.nc.vo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;


*/
/**
 * 交易分录管理Vo<br>
 * @author hu.ding <br>
 * @version 1.0.0 2015年10月10日<br>
 * @see 
 * @since JDK 1.6.0
 *//*

public class BusinessVchManageVo extends FlowStartVo implements Serializable{
	
	*/
/**
	 *   序列化
	 *//*

	private static final long serialVersionUID = 1L;

	//借方金额
	private BigDecimal daccamt;
	
	//贷方金额
	private BigDecimal caccamt;
	
	//分录描述
	private String journaldesc;
	
	//币种
	private String ccydesc;
	
	//会计科目名称
	private String accdesc;
	
	//出账机构信息
	private String bchdesc;
	
	//辅助核算项
	private String assType;
	
	//客户编码
	private String custid;
	
	//合同流水号
	private String busscontno;
	
	private String eventTypeDesc;
	
	private String bussType;
	
	private String datamodule;
	
	*/
/**
	 * 备注
	 *//*

	private String remark;
	
	*/
/**
	 * 科目属性
	 *//*

	private String curraccstatus;
	
	*/
/**
	 * 客户名称
	 *//*

	private String custname;
	
	*/
/**
	 * 交易形态描述
	 *//*

	private String coldesc;
	
	*/
/**
	 * 业务产品
	 *//*

	private String bussdesc;
	
	*/
/**
	 * 业务科目类别
	 *//*

	private String accnotype;
	
	*/
/**
	 * 贷款性质 描述
	 *//*

	private String loantypedesc;
	
	*/
/**
	 * 系统语言
	 *//*

	private String languageid;
	
	*/
/**
	 * 获取custname.
	 * @return the custname
	 *//*

	public String getCustname() {
		return custname;
	}

	*/
/**
	 * 获取bussdesc.
	 * @return the bussdesc
	 *//*

	public String getBussdesc() {
		return bussdesc;
	}

	*/
/**
	 * 设置bussdesc.
	 * @param newbussdesc the bussdesc to set
	 *//*

	public void setBussdesc(String bussdesc) {
		this.bussdesc = bussdesc;
	}

	*/
/**
	 * 获取coldesc.
	 * @return the coldesc
	 *//*

	public String getColdesc() {
		return coldesc;
	}

	*/
/**
	 * 设置coldesc.
	 * @param newcoldesc the coldesc to set
	 *//*

	public void setColdesc(String coldesc) {
		this.coldesc = coldesc;
	}

	*/
/**
	 * 设置custname.
	 * @param newcustname the custname to set
	 *//*

	public void setCustname(String custname) {
		this.custname = custname;
	}

	*/
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.REFCODE
     *
     * @mbggenerated
     *//*

    private Integer refcode;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.VOUCHNO
     *
     * @mbggenerated
     *//*

    private String vouchno;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.ORDERNO
     *
     * @mbggenerated
     *//*

    private Integer orderno;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.CONSUBACCNO
     *
     * @mbggenerated
     *//*

    private String consubaccno;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.SUBACCNO
     *
     * @mbggenerated
     *//*

    private String subaccno;

    
    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.DTCREFCODE
     *
     * @mbggenerated
     *//*

    private Integer dtcrefcode;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.BUSSREFCODE
     *
     * @mbggenerated
     *//*

    private Integer bussrefcode;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.SUITNO
     *
     * @mbggenerated
     *//*

    private Integer suitno;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.TXNO
     *
     * @mbggenerated
     *//*

    private Integer txno;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.TXDATE
     *
     * @mbggenerated
     *//*

    private Date txdate;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.ACCNO
     *
     * @mbggenerated
     *//*

    private String accno;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.DCMARK
     *
     * @mbggenerated
     *//*

    private String dcmark;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.CCYID
     *
     * @mbggenerated
     *//*

    private String ccyid;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.CUSTREFCODE
     *
     * @mbggenerated
     *//*

    private Integer custrefcode;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.ACCAMT
     *
     * @mbggenerated
     *//*

    private BigDecimal accamt;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.VCHDATE
     *
     * @mbggenerated
     *//*

    private Date vchdate;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.EXGRATE
     *
     * @mbggenerated
     *//*

    private BigDecimal exgrate;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.TRANSMITFLAG
     *
     * @mbggenerated
     *//*

    private String transmitflag;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.VCHFRMTXFLAG
     *
     * @mbggenerated
     *//*

    private String vchfrmtxflag;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.BCHID
     *
     * @mbggenerated
     *//*

    private String bchid;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.DWACCNO
     *
     * @mbggenerated
     *//*

    private String dwaccno;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.CLTYPE
     *
     * @mbggenerated
     *//*

    private String cltype;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.DWNO
     *
     * @mbggenerated
     *//*

    private String dwno;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.UPLOADFLAG
     *
     * @mbggenerated
     *//*

    private String uploadflag;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.ECFLAG
     *
     * @mbggenerated
     *//*

    private String ecflag;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.EVENTTYPE
     *
     * @mbggenerated
     *//*

    private Integer eventtype;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.USECLCUSTTYPE
     *
     * @mbggenerated
     *//*

    private String useclcusttype;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.VCHTYPE
     *
     * @mbggenerated
     *//*

    private String vchtype;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.CHKVCHFLAG
     *
     * @mbggenerated
     *//*

    private String chkvchflag;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.LOANTYPE
     *
     * @mbggenerated
     *//*

    private String loantype;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.MBCHTYPE
     *
     * @mbggenerated
     *//*

    private String mbchtype;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.BCHSTATUS
     *
     * @mbggenerated
     *//*

    private String bchstatus;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.DATASTATUS
     *
     * @mbggenerated
     *//*

    private String datastatus;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.ENTITYID
     *
     * @mbggenerated
     *//*

    private String entityid;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.DELFLAG
     *
     * @mbggenerated
     *//*

    private String delflag;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.CREATEUSER
     *
     * @mbggenerated
     *//*

    private String createuser;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.CREATEAGENTUSER
     *
     * @mbggenerated
     *//*

    private String createagentuser;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.CREATEDATE
     *
     * @mbggenerated
     *//*

    private Date createdate;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.EDTID
     *
     * @mbggenerated
     *//*

    private String edtid;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.LASTMODUSER
     *
     * @mbggenerated
     *//*

    private String lastmoduser;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.AGENTUSER
     *
     * @mbggenerated
     *//*

    private String agentuser;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHM.LASTMODDATE
     *
     * @mbggenerated
     *//*

    private Date lastmoddate;

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.REFCODE
     *
     * @return the value of VBTXVCHM.REFCODE
     *
     * @mbggenerated
     *//*

    public Integer getRefcode() {
        return refcode;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.REFCODE
     *
     * @param refcode the value for VBTXVCHM.REFCODE
     *
     * @mbggenerated
     *//*

    public void setRefcode(Integer refcode) {
        PropertyAssert.notNull(refcode);
        PropertyAssert.overPrecision(refcode, 10, 0);
        this.refcode = refcode;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.VOUCHNO
     *
     * @return the value of VBTXVCHM.VOUCHNO
     *
     * @mbggenerated
     *//*

    public String getVouchno() {
        return vouchno;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.VOUCHNO
     *
     * @param vouchno the value for VBTXVCHM.VOUCHNO
     *
     * @mbggenerated
     *//*

    public void setVouchno(String vouchno) {
        PropertyAssert.overLength(vouchno, 40);
        this.vouchno = vouchno == null ? null : vouchno.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.ORDERNO
     *
     * @return the value of VBTXVCHM.ORDERNO
     *
     * @mbggenerated
     *//*

    public Integer getOrderno() {
        return orderno;
    }

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VBTXVCHE.SEQNO
     *
     * @mbggenerated
     *//*

    private Integer seqno;
    
    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHE.SEQNO
     *
     * @return the value of VBTXVCHE.SEQNO
     *
     * @mbggenerated
     *//*

    public Integer getSeqno() {
        return seqno;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHE.SEQNO
     *
     * @param seqno the value for VBTXVCHE.SEQNO
     *
     * @mbggenerated
     *//*

    public void setSeqno(Integer seqno) {
        PropertyAssert.overPrecision(seqno, 10, 0);
        this.seqno = seqno;
    }
    
    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.ORDERNO
     *
     * @param orderno the value for VBTXVCHM.ORDERNO
     *
     * @mbggenerated
     *//*

    public void setOrderno(Integer orderno) {
        PropertyAssert.overPrecision(orderno, 10, 0);
        this.orderno = orderno;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.DTCREFCODE
     *
     * @return the value of VBTXVCHM.DTCREFCODE
     *
     * @mbggenerated
     *//*

    public Integer getDtcrefcode() {
        return dtcrefcode;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.DTCREFCODE
     *
     * @param dtcrefcode the value for VBTXVCHM.DTCREFCODE
     *
     * @mbggenerated
     *//*

    public void setDtcrefcode(Integer dtcrefcode) {
        PropertyAssert.overPrecision(dtcrefcode, 10, 0);
        this.dtcrefcode = dtcrefcode;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.BUSSREFCODE
     *
     * @return the value of VBTXVCHM.BUSSREFCODE
     *
     * @mbggenerated
     *//*

    public Integer getBussrefcode() {
        return bussrefcode;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.BUSSREFCODE
     *
     * @param bussrefcode the value for VBTXVCHM.BUSSREFCODE
     *
     * @mbggenerated
     *//*

    public void setBussrefcode(Integer bussrefcode) {
        PropertyAssert.overPrecision(bussrefcode, 10, 0);
        this.bussrefcode = bussrefcode;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.SUITNO
     *
     * @return the value of VBTXVCHM.SUITNO
     *
     * @mbggenerated
     *//*

    public Integer getSuitno() {
        return suitno;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.SUITNO
     *
     * @param suitno the value for VBTXVCHM.SUITNO
     *
     * @mbggenerated
     *//*

    public void setSuitno(Integer suitno) {
        PropertyAssert.overPrecision(suitno, 10, 0);
        this.suitno = suitno;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.TXNO
     *
     * @return the value of VBTXVCHM.TXNO
     *
     * @mbggenerated
     *//*

    public Integer getTxno() {
        return txno;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.TXNO
     *
     * @param txno the value for VBTXVCHM.TXNO
     *
     * @mbggenerated
     *//*

    public void setTxno(Integer txno) {
        PropertyAssert.overPrecision(txno, 10, 0);
        this.txno = txno;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.TXDATE
     *
     * @return the value of VBTXVCHM.TXDATE
     *
     * @mbggenerated
     *//*

    public Date getTxdate() {
        return txdate;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.TXDATE
     *
     * @param txdate the value for VBTXVCHM.TXDATE
     *
     * @mbggenerated
     *//*

    public void setTxdate(Date txdate) {
        this.txdate = txdate;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.ACCNO
     *
     * @return the value of VBTXVCHM.ACCNO
     *
     * @mbggenerated
     *//*

    public String getAccno() {
        return accno;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.ACCNO
     *
     * @param accno the value for VBTXVCHM.ACCNO
     *
     * @mbggenerated
     *//*

    public void setAccno(String accno) {
        PropertyAssert.overLength(accno, 40);
        this.accno = accno == null ? null : accno.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.DCMARK
     *
     * @return the value of VBTXVCHM.DCMARK
     *
     * @mbggenerated
     *//*

    public String getDcmark() {
        return dcmark;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.DCMARK
     *
     * @param dcmark the value for VBTXVCHM.DCMARK
     *
     * @mbggenerated
     *//*

    public void setDcmark(String dcmark) {
        PropertyAssert.overLength(dcmark, 1);
        this.dcmark = dcmark == null ? null : dcmark.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.CCYID
     *
     * @return the value of VBTXVCHM.CCYID
     *
     * @mbggenerated
     *//*

    public String getCcyid() {
        return ccyid;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.CCYID
     *
     * @param ccyid the value for VBTXVCHM.CCYID
     *
     * @mbggenerated
     *//*

    public void setCcyid(String ccyid) {
        PropertyAssert.overLength(ccyid, 6);
        this.ccyid = ccyid == null ? null : ccyid.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.CUSTREFCODE
     *
     * @return the value of VBTXVCHM.CUSTREFCODE
     *
     * @mbggenerated
     *//*

    public Integer getCustrefcode() {
        return custrefcode;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.CUSTREFCODE
     *
     * @param custrefcode the value for VBTXVCHM.CUSTREFCODE
     *
     * @mbggenerated
     *//*

    public void setCustrefcode(Integer custrefcode) {
        PropertyAssert.overPrecision(custrefcode, 10, 0);
        this.custrefcode = custrefcode;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.ACCAMT
     *
     * @return the value of VBTXVCHM.ACCAMT
     *
     * @mbggenerated
     *//*

    public BigDecimal getAccamt() {
        return accamt;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.ACCAMT
     *
     * @param accamt the value for VBTXVCHM.ACCAMT
     *
     * @mbggenerated
     *//*

    public void setAccamt(BigDecimal accamt) {
        PropertyAssert.overPrecision(accamt, 16, 4);
        this.accamt = accamt;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.VCHDATE
     *
     * @return the value of VBTXVCHM.VCHDATE
     *
     * @mbggenerated
     *//*

    public Date getVchdate() {
        return vchdate;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.VCHDATE
     *
     * @param vchdate the value for VBTXVCHM.VCHDATE
     *
     * @mbggenerated
     *//*

    public void setVchdate(Date vchdate) {
        this.vchdate = vchdate;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.EXGRATE
     *
     * @return the value of VBTXVCHM.EXGRATE
     *
     * @mbggenerated
     *//*

    public BigDecimal getExgrate() {
        return exgrate;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.EXGRATE
     *
     * @param exgrate the value for VBTXVCHM.EXGRATE
     *
     * @mbggenerated
     *//*

    public void setExgrate(BigDecimal exgrate) {
        PropertyAssert.overPrecision(exgrate, 16, 8);
        this.exgrate = exgrate;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.TRANSMITFLAG
     *
     * @return the value of VBTXVCHM.TRANSMITFLAG
     *
     * @mbggenerated
     *//*

    public String getTransmitflag() {
        return transmitflag;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.TRANSMITFLAG
     *
     * @param transmitflag the value for VBTXVCHM.TRANSMITFLAG
     *
     * @mbggenerated
     *//*

    public void setTransmitflag(String transmitflag) {
        PropertyAssert.overLength(transmitflag, 1);
        this.transmitflag = transmitflag == null ? null : transmitflag.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.VCHFRMTXFLAG
     *
     * @return the value of VBTXVCHM.VCHFRMTXFLAG
     *
     * @mbggenerated
     *//*

    public String getVchfrmtxflag() {
        return vchfrmtxflag;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.VCHFRMTXFLAG
     *
     * @param vchfrmtxflag the value for VBTXVCHM.VCHFRMTXFLAG
     *
     * @mbggenerated
     *//*

    public void setVchfrmtxflag(String vchfrmtxflag) {
        PropertyAssert.overLength(vchfrmtxflag, 1);
        this.vchfrmtxflag = vchfrmtxflag == null ? null : vchfrmtxflag.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.BCHID
     *
     * @return the value of VBTXVCHM.BCHID
     *
     * @mbggenerated
     *//*

    public String getBchid() {
        return bchid;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.BCHID
     *
     * @param bchid the value for VBTXVCHM.BCHID
     *
     * @mbggenerated
     *//*

    public void setBchid(String bchid) {
        PropertyAssert.overLength(bchid, 20);
        this.bchid = bchid == null ? null : bchid.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.DWACCNO
     *
     * @return the value of VBTXVCHM.DWACCNO
     *
     * @mbggenerated
     *//*

    public String getDwaccno() {
        return dwaccno;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.DWACCNO
     *
     * @param dwaccno the value for VBTXVCHM.DWACCNO
     *
     * @mbggenerated
     *//*

    public void setDwaccno(String dwaccno) {
        PropertyAssert.overLength(dwaccno, 60);
        this.dwaccno = dwaccno == null ? null : dwaccno.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.CLTYPE
     *
     * @return the value of VBTXVCHM.CLTYPE
     *
     * @mbggenerated
     *//*

    public String getCltype() {
        return cltype;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.CLTYPE
     *
     * @param cltype the value for VBTXVCHM.CLTYPE
     *
     * @mbggenerated
     *//*

    public void setCltype(String cltype) {
        PropertyAssert.overLength(cltype, 1);
        this.cltype = cltype == null ? null : cltype.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.DWNO
     *
     * @return the value of VBTXVCHM.DWNO
     *
     * @mbggenerated
     *//*

    public String getDwno() {
        return dwno;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.DWNO
     *
     * @param dwno the value for VBTXVCHM.DWNO
     *
     * @mbggenerated
     *//*

    public void setDwno(String dwno) {
        PropertyAssert.overLength(dwno, 8);
        this.dwno = dwno == null ? null : dwno.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.UPLOADFLAG
     *
     * @return the value of VBTXVCHM.UPLOADFLAG
     *
     * @mbggenerated
     *//*

    public String getUploadflag() {
        return uploadflag;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.UPLOADFLAG
     *
     * @param uploadflag the value for VBTXVCHM.UPLOADFLAG
     *
     * @mbggenerated
     *//*

    public void setUploadflag(String uploadflag) {
        PropertyAssert.overLength(uploadflag, 1);
        this.uploadflag = uploadflag == null ? null : uploadflag.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.ECFLAG
     *
     * @return the value of VBTXVCHM.ECFLAG
     *
     * @mbggenerated
     *//*

    public String getEcflag() {
        return ecflag;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.ECFLAG
     *
     * @param ecflag the value for VBTXVCHM.ECFLAG
     *
     * @mbggenerated
     *//*

    public void setEcflag(String ecflag) {
        this.ecflag = ecflag == null ? null : ecflag.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.EVENTTYPE
     *
     * @return the value of VBTXVCHM.EVENTTYPE
     *
     * @mbggenerated
     *//*

    public Integer getEventtype() {
        return eventtype;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.EVENTTYPE
     *
     * @param eventtype the value for VBTXVCHM.EVENTTYPE
     *
     * @mbggenerated
     *//*

    public void setEventtype(Integer eventtype) {
        PropertyAssert.overPrecision(eventtype, 10, 0);
        this.eventtype = eventtype;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.USECLCUSTTYPE
     *
     * @return the value of VBTXVCHM.USECLCUSTTYPE
     *
     * @mbggenerated
     *//*

    public String getUseclcusttype() {
        return useclcusttype;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.USECLCUSTTYPE
     *
     * @param useclcusttype the value for VBTXVCHM.USECLCUSTTYPE
     *
     * @mbggenerated
     *//*

    public void setUseclcusttype(String useclcusttype) {
        PropertyAssert.overLength(useclcusttype, 1);
        this.useclcusttype = useclcusttype == null ? null : useclcusttype.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.VCHTYPE
     *
     * @return the value of VBTXVCHM.VCHTYPE
     *
     * @mbggenerated
     *//*

    public String getVchtype() {
        return vchtype;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.VCHTYPE
     *
     * @param vchtype the value for VBTXVCHM.VCHTYPE
     *
     * @mbggenerated
     *//*

    public void setVchtype(String vchtype) {
        PropertyAssert.overLength(vchtype, 1);
        this.vchtype = vchtype == null ? null : vchtype.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.CHKVCHFLAG
     *
     * @return the value of VBTXVCHM.CHKVCHFLAG
     *
     * @mbggenerated
     *//*

    public String getChkvchflag() {
        return chkvchflag;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.CHKVCHFLAG
     *
     * @param chkvchflag the value for VBTXVCHM.CHKVCHFLAG
     *
     * @mbggenerated
     *//*

    public void setChkvchflag(String chkvchflag) {
        PropertyAssert.overLength(chkvchflag, 1);
        this.chkvchflag = chkvchflag == null ? null : chkvchflag.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.LOANTYPE
     *
     * @return the value of VBTXVCHM.LOANTYPE
     *
     * @mbggenerated
     *//*

    public String getLoantype() {
        return loantype;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.LOANTYPE
     *
     * @param loantype the value for VBTXVCHM.LOANTYPE
     *
     * @mbggenerated
     *//*

    public void setLoantype(String loantype) {
        PropertyAssert.overLength(loantype, 1);
        this.loantype = loantype == null ? null : loantype.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.MBCHTYPE
     *
     * @return the value of VBTXVCHM.MBCHTYPE
     *
     * @mbggenerated
     *//*

    public String getMbchtype() {
        return mbchtype;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.MBCHTYPE
     *
     * @param mbchtype the value for VBTXVCHM.MBCHTYPE
     *
     * @mbggenerated
     *//*

    public void setMbchtype(String mbchtype) {
        PropertyAssert.overLength(mbchtype, 40);
        this.mbchtype = mbchtype == null ? null : mbchtype.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.BCHSTATUS
     *
     * @return the value of VBTXVCHM.BCHSTATUS
     *
     * @mbggenerated
     *//*

    public String getBchstatus() {
        return bchstatus;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.BCHSTATUS
     *
     * @param bchstatus the value for VBTXVCHM.BCHSTATUS
     *
     * @mbggenerated
     *//*

    public void setBchstatus(String bchstatus) {
        PropertyAssert.overLength(bchstatus, 1);
        this.bchstatus = bchstatus == null ? null : bchstatus.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.DATASTATUS
     *
     * @return the value of VBTXVCHM.DATASTATUS
     *
     * @mbggenerated
     *//*

    public String getDatastatus() {
        return datastatus;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.DATASTATUS
     *
     * @param datastatus the value for VBTXVCHM.DATASTATUS
     *
     * @mbggenerated
     *//*

    public void setDatastatus(String datastatus) {
        PropertyAssert.overLength(datastatus, 20);
        this.datastatus = datastatus == null ? null : datastatus.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.ENTITYID
     *
     * @return the value of VBTXVCHM.ENTITYID
     *
     * @mbggenerated
     *//*

    public String getEntityid() {
        return entityid;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.ENTITYID
     *
     * @param entityid the value for VBTXVCHM.ENTITYID
     *
     * @mbggenerated
     *//*

    public void setEntityid(String entityid) {
        PropertyAssert.overLength(entityid, 100);
        this.entityid = entityid == null ? null : entityid.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.DELFLAG
     *
     * @return the value of VBTXVCHM.DELFLAG
     *
     * @mbggenerated
     *//*

    public String getDelflag() {
        return delflag;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.DELFLAG
     *
     * @param delflag the value for VBTXVCHM.DELFLAG
     *
     * @mbggenerated
     *//*

    public void setDelflag(String delflag) {
        PropertyAssert.overLength(delflag, 1);
        this.delflag = delflag == null ? null : delflag.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.CREATEUSER
     *
     * @return the value of VBTXVCHM.CREATEUSER
     *
     * @mbggenerated
     *//*

    public String getCreateuser() {
        return createuser;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.CREATEUSER
     *
     * @param createuser the value for VBTXVCHM.CREATEUSER
     *
     * @mbggenerated
     *//*

    public void setCreateuser(String createuser) {
        PropertyAssert.overLength(createuser, 40);
        this.createuser = createuser == null ? null : createuser.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.CREATEAGENTUSER
     *
     * @return the value of VBTXVCHM.CREATEAGENTUSER
     *
     * @mbggenerated
     *//*

    public String getCreateagentuser() {
        return createagentuser;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.CREATEAGENTUSER
     *
     * @param createagentuser the value for VBTXVCHM.CREATEAGENTUSER
     *
     * @mbggenerated
     *//*

    public void setCreateagentuser(String createagentuser) {
        PropertyAssert.overLength(createagentuser, 40);
        this.createagentuser = createagentuser == null ? null : createagentuser.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.CREATEDATE
     *
     * @return the value of VBTXVCHM.CREATEDATE
     *
     * @mbggenerated
     *//*

    public Date getCreatedate() {
        return createdate;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.CREATEDATE
     *
     * @param createdate the value for VBTXVCHM.CREATEDATE
     *
     * @mbggenerated
     *//*

    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.EDTID
     *
     * @return the value of VBTXVCHM.EDTID
     *
     * @mbggenerated
     *//*

    public String getEdtid() {
        return edtid;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.EDTID
     *
     * @param edtid the value for VBTXVCHM.EDTID
     *
     * @mbggenerated
     *//*

    public void setEdtid(String edtid) {
        PropertyAssert.overLength(edtid, 6);
        this.edtid = edtid == null ? null : edtid.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.LASTMODUSER
     *
     * @return the value of VBTXVCHM.LASTMODUSER
     *
     * @mbggenerated
     *//*

    public String getLastmoduser() {
        return lastmoduser;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.LASTMODUSER
     *
     * @param lastmoduser the value for VBTXVCHM.LASTMODUSER
     *
     * @mbggenerated
     *//*

    public void setLastmoduser(String lastmoduser) {
        PropertyAssert.overLength(lastmoduser, 40);
        this.lastmoduser = lastmoduser == null ? null : lastmoduser.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.AGENTUSER
     *
     * @return the value of VBTXVCHM.AGENTUSER
     *
     * @mbggenerated
     *//*

    public String getAgentuser() {
        return agentuser;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.AGENTUSER
     *
     * @param agentuser the value for VBTXVCHM.AGENTUSER
     *
     * @mbggenerated
     *//*

    public void setAgentuser(String agentuser) {
        PropertyAssert.overLength(agentuser, 40);
        this.agentuser = agentuser == null ? null : agentuser.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VBTXVCHM.LASTMODDATE
     *
     * @return the value of VBTXVCHM.LASTMODDATE
     *
     * @mbggenerated
     *//*

    public Date getLastmoddate() {
        return lastmoddate;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VBTXVCHM.LASTMODDATE
     *
     * @param lastmoddate the value for VBTXVCHM.LASTMODDATE
     *
     * @mbggenerated
     *//*

    public void setLastmoddate(Date lastmoddate) {
        this.lastmoddate = lastmoddate;
    }

	*/
/**
	 * 获取daccamt.
	 * @return the daccamt
	 *//*

	public BigDecimal getDaccamt() {
		return daccamt;
	}

	*/
/**
	 * 设置daccamt.
	 * @param newdaccamt the daccamt to set
	 *//*

	public void setDaccamt(BigDecimal daccamt) {
		this.daccamt = daccamt;
	}

	*/
/**
	 * 获取caccamt.
	 * @return the caccamt
	 *//*

	public BigDecimal getCaccamt() {
		return caccamt;
	}

	*/
/**
	 * 设置caccamt.
	 * @param newcaccamt the caccamt to set
	 *//*

	public void setCaccamt(BigDecimal caccamt) {
		this.caccamt = caccamt;
	}

	*/
/**
	 * 获取journaldesc.
	 * @return the journaldesc
	 *//*

	public String getJournaldesc() {
		return journaldesc;
	}

	*/
/**
	 * 设置journaldesc.
	 * @param newjournaldesc the journaldesc to set
	 *//*

	public void setJournaldesc(String journaldesc) {
		this.journaldesc = journaldesc;
	}

	*/
/**
	 * 获取ccydesc.
	 * @return the ccydesc
	 *//*

	public String getCcydesc() {
		return ccydesc;
	}

	*/
/**
	 * 设置ccydesc.
	 * @param newccydesc the ccydesc to set
	 *//*

	public void setCcydesc(String ccydesc) {
		this.ccydesc = ccydesc;
	}

	*/
/**
	 * 获取accdesc.
	 * @return the accdesc
	 *//*

	public String getAccdesc() {
		return accdesc;
	}

	*/
/**
	 * 设置accdesc.
	 * @param newaccdesc the accdesc to set
	 *//*

	public void setAccdesc(String accdesc) {
		this.accdesc = accdesc;
	}

	*/
/**
	 * 获取bchdesc.
	 * @return the bchdesc
	 *//*

	public String getBchdesc() {
		return bchdesc;
	}

	*/
/**
	 * 设置bchdesc.
	 * @param newbchdesc the bchdesc to set
	 *//*

	public void setBchdesc(String bchdesc) {
		this.bchdesc = bchdesc;
	}

	*/
/**
	 * 获取accnotype.
	 * @return the accnotype
	 *//*

	public String getAccnotype() {
		return accnotype;
	}

	*/
/**
	 * 设置accnotype.
	 * @param newaccnotype the accnotype to set
	 *//*

	public void setAccnotype(String accnotype) {
		this.accnotype = accnotype;
	}

	*/
/**
	 * 获取subaccno.
	 * @return the subaccno
	 *//*

	public String getSubaccno() {
		return subaccno;
	}

	*/
/**
	 * 设置subaccno.
	 * @param newsubaccno the subaccno to set
	 *//*

	public void setSubaccno(String subaccno) {
		this.subaccno = subaccno;
	}

	*/
/**
	 * 获取consubaccno.
	 * @return the consubaccno
	 *//*

	public String getConsubaccno() {
		return consubaccno;
	}

	*/
/**
	 * 设置consubaccno.
	 * @param newconsubaccno the consubaccno to set
	 *//*

	public void setConsubaccno(String consubaccno) {
		this.consubaccno = consubaccno;
	}

	*/
/**
	 * 获取curraccstatus.
	 * @return the curraccstatus
	 *//*

	public String getCurraccstatus() {
		return curraccstatus;
	}

	*/
/**
	 * 设置curraccstatus.
	 * @param newcurraccstatus the curraccstatus to set
	 *//*

	public void setCurraccstatus(String curraccstatus) {
		this.curraccstatus = curraccstatus;
	}

	*/
/**
	 * 获取remark.
	 * @return the remark
	 *//*

	public String getRemark() {
		return remark;
	}

	*/
/**
	 * 设置remark.
	 * @param newremark the remark to set
	 *//*

	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	*/
/**
	 * 获取loantypedesc.
	 * @return the loantypedesc
	 *//*

	public String getLoantypedesc() {
		return loantypedesc;
	}

	*/
/**
	 * 设置loantypedesc.
	 * @param loantypedesc the loantypedesc to set
	 *//*

	public void setLoantypedesc(String loantypedesc) {
		this.loantypedesc = loantypedesc;
	}
	
	*/
/**
	 * 获取languageid.
	 * @return the languageid
	 *//*

	public String getLanguageid() {
		return languageid;
	}

	*/
/**
	 * 设置languageid.
	 * @param languageid the languageid to set
	 *//*

	public void setLanguageid(String languageid) {
		this.languageid = languageid;
	}

	public String getAssType() {
		return assType;
	}

	public void setAssType(String assType) {
		this.assType = assType;
	}

	public String getCustid() {
		return custid;
	}

	public void setCustid(String custid) {
		this.custid = custid;
	}

	public String getBusscontno() {
		return busscontno;
	}

	public void setBusscontno(String busscontno) {
		this.busscontno = busscontno;
	}

	public String getEventTypeDesc() {
		return eventTypeDesc;
	}

	public void setEventTypeDesc(String eventTypeDesc) {
		this.eventTypeDesc = eventTypeDesc;
	}

	public String getBussType() {
		return bussType;
	}

	public void setBussType(String bussType) {
		this.bussType = bussType;
	}

	public String getDatamodule() {
		return datamodule;
	}

	public void setDatamodule(String datamodule) {
		this.datamodule = datamodule;
	}


}
*/
