#端口
server:
  port: 8888
#环境
spring:
  profiles:
    active: local
    #Oracle数据库
    datasource:
      url: jdbc:oracle:thin:@192.168.6.102:1521:helowin
      #
      username: system
      password: oracle
      driver-class-name: oracle.jdbc.OracleDriver
#日志
logging:
  config: classpath:logback/logback-base.xml

